### ISSUE TITLE
'config.h' file not found 

### ISSUE THREAD

**Issue by karthinalliyappan** [voxeet/react-native-voxeet-conferencekit#1]
'config.h' file not found --> Got the error.

Environment Setup:
Xcode : 10.1
Operating system : 10.3.1
React-native : 0.57.6

Attached the screen shot for reference.
![screen shot 2018 11 27 at 6 07 02 pm](https://user-images.githubusercontent.com/26541759/49083348-53beb200-f272-11e8-8b08-f76687b8612b.png)

**Comment by karthinalliyappan** [comment]
Followed the below steps:
![screen shot 2018-11-27 at 5 43 47 pm](https://user-images.githubusercontent.com/26541759/49083372-63d69180-f272-11e8-987b-780a335317c6.png)

**Comment by Comanga** [comment]
third-party is a react-native library, what happened if you generate a brand new project with: `react-native init Test` and try to building it without Voxeet?

**Comment by karthinalliyappan** [comment]
I'm tried the ` react-native init Test ` and build the app its working.

**Comment by Comanga** [comment]
Well, is it possible to push a project with your error on github so I can test it?

react-native-cli: 2.0.1
react-native: 0.57.5 (will update)

**Comment by codlab** [comment]
Issue closed for inactivity. Project working on both ends
