### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by livindead** [voxeet/react-native-voxeet-conferencekit#4]
**Describe the bug**

After run command 
npm install @voxeet/react-native-voxeet-conferencekit --save

Console error 

@voxeet/react-native-voxeet-conferencekit@0.1.1 postinstall /Users/light/workflow/react/akbars/AkbarsProject/node_modules/@voxeet/react-native-voxeet-conferencekit
> bash build_ios_frameworks.sh

> installing ios dependencies (carthage)
build_ios_frameworks.sh: line 4: carthage: command not found
npm WARN @voxeet/react-components@0.32.1 requires a peer of @voxeet/voxeet-web-sdk@1.9.2-alpha.2 but none is installed. You must install peer dependencies yourself.
npm WARN @voxeet/voxeet-web-sdk@1.9.3 requires a peer of @voxeet/media-engine@0.16.0 but none is installed. You must install peer dependencies yourself.
npm WARN expo-google-sign-in@2.0.0 requires a peer of react-native@^0.55.4 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-reanimated@1.0.0-alpha.11 requires a peer of react@16.0.0-alpha.6 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-reanimated@1.0.0-alpha.11 requires a peer of react-native@^0.44.1 but none is installed. You must install peer dependencies yourself.
npm WARN url-loader@1.1.2 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @voxeet/react-native-voxeet-conferencekit@0.1.1 requires a peer of react-native@^0.55.4 but none is installed. You must install peer dependencies yourself.

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @voxeet/react-native-voxeet-conferencekit@0.1.1 postinstall: `bash build_ios_frameworks.sh`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @voxeet/react-native-voxeet-conferencekit@0.1.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

MacOS 10.14.4
react-native cli 0.57.1

**Comment by codlab** [comment]
```
build_ios_frameworks.sh: line 4: carthage: command not found
```

Please install [Carthage](https://github.com/Carthage/Carthage) on your Mac

**Comment by livindead** [comment]
> ```
> build_ios_frameworks.sh: line 4: carthage: command not found
> ```
> 
> Please install [Carthage](https://github.com/Carthage/Carthage) on your Mac

And if you work under Windows ?

**Comment by codlab** [comment]
It'll likely won't work for now

**Comment by livindead** [comment]
the error is still there

 bash build_ios_frameworks.sh

> installing ios dependencies (carthage)
*** Fetching voxeet-ios-conferencekit
*** Fetching voxeet-ios-sdk
*** Fetching Kingfisher
*** Checking out voxeet-ios-conferencekit at "1.1.9"
*** Checking out voxeet-ios-sdk at "1.3.9"
*** Checking out Kingfisher at "b5abf719d7e7428895542ebd5f0faa115b41a262"
*** xcodebuild output can be found in /var/folders/gs/89fcc4hd00q8n7mpf9y48f0m0000gn/T/carthage-xcodebuild.cQmMGs.log
*** Downloading voxeet-ios-sdk.framework binary at "1.3.9"
***  Skipped installing voxeet-ios-sdk.framework binary due to the error:
	"Incompatible Swift version - framework was built with 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5) and the local version is 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3)."

    Falling back to building from the source
*** Building scheme "Kingfisher" in Kingfisher.xcworkspace
*** Skipped building voxeet-ios-sdk due to the error:
Dependency "voxeet-ios-sdk" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/voxeet/voxeet-ios-sdk/issues/new
*** Building scheme "VoxeetConferenceKit" in VoxeetConferenceKit.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/light/workflow/react/akbars/AkbarsProject/node_modules/@voxeet/react-native-voxeet-conferencekit/ios/Carthage/Checkouts/voxeet-ios-conferencekit/VoxeetConferenceKit.xcodeproj -scheme VoxeetConferenceKit -configuration Release -derivedDataPath /Users/light/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/voxeet-ios-conferencekit/1.1.9 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/gs/89fcc4hd00q8n7mpf9y48f0m0000gn/T/voxeet-ios-conferencekit SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/light/workflow/react/akbars/AkbarsProject/node_modules/@voxeet/react-native-voxeet-conferencekit/ios/Carthage/Checkouts/voxeet-ios-conferencekit)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/gs/89fcc4hd00q8n7mpf9y48f0m0000gn/T/carthage-xcodebuild.cQmMGs.log
npm WARN @voxeet/react-components@0.32.1 requires a peer of @voxeet/voxeet-web-sdk@1.9.2-alpha.2 but none is installed. You must install peer dependencies yourself.
npm WARN @voxeet/voxeet-web-sdk@1.9.3 requires a peer of @voxeet/media-engine@0.16.0 but none is installed. You must install peer dependencies yourself.
npm WARN expo-google-sign-in@2.0.0 requires a peer of react-native@^0.55.4 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-reanimated@1.0.0-alpha.11 requires a peer of react@16.0.0-alpha.6 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-reanimated@1.0.0-alpha.11 requires a peer of react-native@^0.44.1 but none is installed. You must install peer dependencies yourself.
npm WARN url-loader@1.1.2 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @voxeet/react-native-voxeet-conferencekit@0.1.1 requires a peer of react-native@^0.55.4 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @voxeet/react-native-voxeet-conferencekit@0.1.1 postinstall: `bash build_ios_frameworks.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @voxeet/react-native-voxeet-conferencekit@0.1.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by codlab** [comment]
```
Incompatible Swift version - framework was built with 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5) and the local version is 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3).
```

An error is still there and concern your XCode installation. Please check that you are using the latest version of the XCode environment available 

@VTCoco should be able to give more information if needed

**Comment by livindead** [comment]
How i can check successful instalation ? 
Does voxeet support the Expo cli ?
I only found old example 
https://github.com/voxeet/voxeet-rn-conferencekit/blob/master/src/components/Voxeet.js
but this it douesnt work

**Comment by livindead** [comment]
`** BUILD FAILED **


The following build commands failed:
	CompileC /Users/light/workflow/react/Awe/ios/build/Awe/Build/Intermediates.noindex/RNVoxeetConferencekit.build/Debug-iphonesimulator/RNVoxeetConferencekit.build/Objects-normal/x86_64/RNVoxeetConferencekit.o /Users/light/workflow/react/Awe/node_modules/@voxeet/react-native-voxeet-conferencekit/ios/RNVoxeetConferencekit/RNVoxeetConferencekit.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)`

**Comment by codlab** [comment]
Please open a proper issue for this specific issue and provide the actual error. Thanks a lot ;)
